name: Build Executeable 

on: 
    push: 
        branches: 
            - develop
    workflow_dispatch: 

jobs:
    build_win_x86: 
        runs-on: windows-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
                  architecture: x86

            - name: Install Dependencies 
              run: pip install -r requirements.txt
            
            - name: Install Pywin32
              run: pip install pywin32
            
            - name: Create Executeable
              run: pyinstaller --hiddenimport win32timezone -F src/browsermon.py
            
            - name: Prepare files for upload
              run: |
                mkdir artifact
                copy dist\browsermon.exe artifact\
                cp README.md artifact/
                cp browsermon.conf artifact/
                cp win_install.ps1 artifact/
                cp win_uninstall.ps1 artifact/

            - name: Create Troubleshooter exe 
              run: pyinstaller -F troubleshoot/browsermon_ts.py
          
            - name: Copy troubeshooter executeable
              run: copy dist\browsermon_ts.exe artifact\
            
            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                name: browsermon_win_x86
                path: artifact/

    build_win_x64: 
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
                  architecture: x64

            - name: Install Dependencies 
              run: pip install -r requirements.txt
            
            - name: Install Pywin32
              run: pip install pywin32
            
            - name: Create Executeable
              run: pyinstaller --hiddenimport win32timezone -F src/browsermon.py
            
            - name: Prepare files for upload
              run: |
                mkdir artifact
                copy dist\browsermon.exe artifact\
                cp README.md artifact/
                cp browsermon.conf artifact/
                cp win_install.ps1 artifact/
                cp win_uninstall.ps1 artifact/
            
            - name: Create Troubleshooter exe 
              run: pyinstaller -F troubleshoot/browsermon_ts.py
          
            - name: Copy troubeshooter executeable
              run: copy dist\browsermon_ts.exe artifact\
            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                name: browsermon_win_x64
                path: artifact/
    
    build_linux_x86:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
                  architecture: x64

            - name: Install Dependencies 
              run: pip install -r requirements.txt
            
            - name: Create Executeable
              run: pyinstaller -F src/browsermon.py
            
            - name: Prepare files for upload
              run: |
                mkdir artifact
                cp dist/browsermon artifact/ 
                cp -r service/ artifact/
                cp README.md artifact/
                cp browsermon.conf artifact/
                cp linux_install.sh artifact/
                cp linux_uninstall.sh artifact/
            
            - name: Create Troubleshooter exe 
              run: pyinstaller -F troubleshoot/browsermon_ts.py
          
            - name: Copy troubeshooter executeable
              run: cp dist/browsermon_ts artifact/
            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                name: browsermon_linux_x64
                path: artifact/