name: Browsermon exe with PyInstaller - Windows

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: .

    - uses: actions/upload-artifact@v3
      with:
        name: browsermon.exe
        path: dist/*
